services:

  # PostgreSQL — source OLTP + warehouse
  postgres:
    image: postgres:15
    container_name: ecommerce_oltp
    restart: unless-stopped
    environment:
      POSTGRES_USER: deuser
      POSTGRES_PASSWORD: depass
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./phase-1-modeling/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deuser -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin — visual DB browser
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin   # persists server registrations
    depends_on:
      - postgres

  # Redis — message broker for Airflow
  redis:
    image: redis:7
    container_name: ecommerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # Zookeeper — required by Kafka
  # Manages Kafka broker metadata and coordination
  # Think of it as the cluster manager
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ecommerce_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

    
    # Kafka Broker
    # The actual message streaming service
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ecommerce_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"       # external access (your Python scripts)
      - "29092:29092"     # internal Docker network access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Two listeners:
      # PLAINTEXT       → for containers inside Docker network
      # PLAINTEXT_HOST  → for connections from your machine (Python scripts)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 5
 
  # Kafka UI — visual topic/message browser
  # Like pgAdmin but for Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce_kafka_ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8090:8080"       # use 8090 to avoid conflict with Airflow on 8080
    environment:
      KAFKA_CLUSTERS_0_NAME: ecommerce
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092


  # Airflow common config
  x-airflow-common: &airflow-common
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://deuser:depass@postgres/ecommerce_db
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://deuser:depass@postgres/ecommerce_db
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'ecommerce_secret_key_123'
      ECOMMERCE_DB_HOST: postgres
      ECOMMERCE_DB_PORT: 5432
      ECOMMERCE_DB_NAME: ecommerce_db
      ECOMMERCE_DB_USER: deuser
      ECOMMERCE_DB_PASSWORD: depass
    volumes:
      - ./phase-2-batch-pipeline/dags:/opt/airflow/dags
      - ./phase-2-batch-pipeline/etl:/opt/airflow/etl
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  # Airflow Init — runs once to set up DB
  airflow-init:
    <<: *airflow-common
    container_name: ecommerce_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --password admin123 \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: on-failure

  # Airflow Webserver — UI at localhost:8080
  airflow-webserver:
    <<: *airflow-common
    container_name: ecommerce_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - airflow-init

  # Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: ecommerce_airflow_scheduler
    command: scheduler
    restart: unless-stopped
    depends_on:
      - airflow-init

  # Airflow Worker
  airflow-worker:
    <<: *airflow-common
    container_name: ecommerce_airflow_worker
    command: celery worker
    restart: unless-stopped
    depends_on:
      - airflow-init

volumes:
  postgres_data:
  airflow_logs:
  pgadmin_data: